openapi: 3.0.3
info:
  title: Credit Card Payment System API
  version: 1.0.0
  description: API documentation for the Credit Card Payment System
paths:
  /api/accounts/login/:
    post:
      operationId: accounts_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/accounts/logout/:
    post:
      operationId: accounts_logout_create
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/me/:
    get:
      operationId: accounts_me_retrieve
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/register/:
    post:
      operationId: accounts_register_create
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/token/refresh/:
    post:
      operationId: accounts_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/cards/:
    post:
      operationId: cards_create
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/cards/{card_id}/:
    delete:
      operationId: cards_destroy
      parameters:
      - in: path
        name: card_id
        schema:
          type: integer
        required: true
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/cards/my-cards/:
    get:
      operationId: cards_my_cards_retrieve
      tags:
      - cards
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/payments/history/:
    get:
      operationId: payments_history_list
      tags:
      - payments
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
          description: ''
  /api/payments/payments/:
    post:
      operationId: payments_payments_create
      tags:
      - payments
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/payments/transactions/admin/export/:
    get:
      operationId: payments_transactions_admin_export_retrieve
      tags:
      - payments
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    StatusEnum:
      enum:
      - PENDING
      - SUCCESS
      - FAILED
      type: string
      description: |-
        * `PENDING` - Pending
        * `SUCCESS` - Success
        * `FAILED` - Failed
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        card:
          type: integer
          nullable: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        payment_id:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - created_at
      - id
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
