# Generated by Django 5.2.6 on 2026-10-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('READ_ONLY', 'Read-Only')], default='READ_ONLY', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CARD_BLOCKED', 'Card blocked'), ('CARD_UNBLOCKED', 'Card unblocked'), ('CREDIT_LIMIT_UPDATED', 'Credit limit updated')], max_length=40)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx')],
            },
        ),
    ]
