# Generated by Django 5.2.6 on 2026-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
            preserve_default=False,
        ),
    ]
