# Generated by Django 5.2.6 on 2026-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_available_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
