# Generated by Django 5.2.6 on 2026-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraud_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_status',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('FLAGGED', 'Flagged'), ('REVIEWED', 'Reviewed')], db_index=True, default='CLEAR', max_length=20),
        ),
    ]
